"""OAuthState model for CSRF protection in OAuth flows."""
from sqlalchemy import Column, String, DateTime, ForeignKey
from sqlalchemy import func
from app.config.database import Base


class OAuthState(Base):
    """Persisted OAuth state token, consumed once on callback.

    Each /oauth/url request generates a row here.  The matching
    /oauth/callback looks up and deletes the row, proving the callback
    was initiated by the same server that generated the URL.  Rows
    older than *expires_at* are treated as stale and rejected.
    """
    __tablename__ = "oauth_states"

    id = Column(String(36), primary_key=True)                          # UUID, generated by the router
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    state_token = Column(String(128), unique=True, index=True, nullable=False)  # "{user_id}:{uuid}"
    created_at = Column(DateTime, default=func.now(), nullable=False)
    expires_at = Column(DateTime, nullable=False)                      # set to created_at + 10 min
