"""add pricing table and update companies and users

Revision ID: 92c60abdec3f
Revises: c8d18de4df5c
Create Date: 2025-12-15 22:51:49.999258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c60abdec3f'
down_revision = 'c8d18de4df5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=False),
    sa.Column('max_domains', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('yearly_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('payable', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('price_plan_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'companies', 'pricing', ['price_plan_id'], ['id'])

    # Update users table notification defaults from 'enabled' to 'disabled'
    # MySQL syntax for changing column defaults
    op.execute("ALTER TABLE users MODIFY COLUMN notifications VARCHAR(20) NOT NULL DEFAULT 'disabled'")
    op.execute("ALTER TABLE users MODIFY COLUMN slack VARCHAR(20) NOT NULL DEFAULT 'disabled'")
    op.execute("ALTER TABLE users MODIFY COLUMN teams VARCHAR(20) NOT NULL DEFAULT 'disabled'")
    op.execute("ALTER TABLE users MODIFY COLUMN telegram VARCHAR(20) NOT NULL DEFAULT 'disabled'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert users table notification defaults back to 'enabled'
    # MySQL syntax for changing column defaults
    op.execute("ALTER TABLE users MODIFY COLUMN telegram VARCHAR(20) NOT NULL DEFAULT 'enabled'")
    op.execute("ALTER TABLE users MODIFY COLUMN teams VARCHAR(20) NOT NULL DEFAULT 'enabled'")
    op.execute("ALTER TABLE users MODIFY COLUMN slack VARCHAR(20) NOT NULL DEFAULT 'enabled'")
    op.execute("ALTER TABLE users MODIFY COLUMN notifications VARCHAR(20) NOT NULL DEFAULT 'enabled'")

    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'price_plan_id')
    op.drop_column('companies', 'payable')
    op.drop_table('pricing')
    # ### end Alembic commands ###
