"""add deleted_at to companies table

Revision ID: c8d18de4df5c
Revises: af0273fbba2d
Create Date: 2025-12-15 22:42:01.461565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d18de4df5c'
down_revision = 'af0273fbba2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'deleted_at')
    # ### end Alembic commands ###
