"""add_discord_multi_channel_support

Revision ID: 30057e622415
Revises: add_teams_table
Create Date: 2025-12-22 21:50:55.027910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30057e622415'
down_revision = 'add_teams_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping idx_cases_links_case_id - needed by foreign key constraint
    # op.drop_index('idx_cases_links_case_id', table_name='cases_links')
    op.add_column('discord', sa.Column('guild_name', sa.String(length=255), nullable=True, comment='Discord server (guild) name - NULL for DMs'))
    op.add_column('discord', sa.Column('channel_name', sa.String(length=255), nullable=True, comment='Discord channel name - NULL for DMs'))
    op.alter_column('discord', 'discord_user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='Discord user ID',
               existing_nullable=False)
    op.alter_column('discord', 'guild_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='Discord server (guild) ID - NULL for DMs',
               existing_nullable=True)
    op.alter_column('discord', 'channel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='Discord channel ID - NULL for DMs',
               existing_nullable=True)
    op.alter_column('discord', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Discord username',
               existing_nullable=True)
    op.alter_column('discord', 'global_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Discord display name',
               existing_nullable=True)
    op.alter_column('discord', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='Status of Discord integration: DISABLED, ENABLED, or ACTIVE',
               existing_comment='Status of Discord connection: Disabled, Enabled, Active, or Inactive',
               existing_nullable=False,
               existing_server_default=sa.text("'Disabled'"))
    op.alter_column('discord', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Soft delete timestamp',
               existing_nullable=True)
    op.drop_index('idx_discord_guild', table_name='discord')
    op.drop_index('idx_discord_uid', table_name='discord')
    op.drop_index('uq_discord_user_account', table_name='discord')
    op.create_unique_constraint('uq_user_guild_channel', 'discord', ['user_id', 'guild_id', 'channel_id'])
    op.alter_column('slack', 'channel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='DM channel ID (slack_user_id) or group channel ID',
               existing_nullable=False)
    op.alter_column('slack', 'channel_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Channel name for group channels, NULL for DMs',
               existing_nullable=True)
    op.drop_index('idx_slack_user_id', table_name='slack')
    op.drop_index('idx_slack_workspace_id', table_name='slack')
    op.drop_index('uq_slack_user_workspace_channel', table_name='slack')
    op.drop_index('idx_teams_tenant', table_name='teams')
    op.drop_index('idx_teams_user_id', table_name='teams')
    op.drop_index('uq_teams_user_tenant', table_name='teams')
    op.alter_column('telegram', 'telegram_user_id',
               existing_type=mysql.BIGINT(),
               comment='Telegram user ID who connected this chat',
               existing_nullable=True)
    op.alter_column('telegram', 'channel_id',
               existing_type=mysql.BIGINT(),
               comment="Chat ID: user's chat_id for DMs, group chat_id for groups",
               existing_nullable=False)
    op.alter_column('telegram', 'chat_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='Type of chat: private, group, supergroup, or channel',
               existing_nullable=False,
               existing_server_default=sa.text("'private'"))
    op.alter_column('telegram', 'chat_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Chat title for groups/channels, NULL for DMs',
               existing_nullable=True)
    op.alter_column('telegram', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment="User's Telegram username",
               existing_nullable=True)
    op.alter_column('telegram', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment="User's first name",
               existing_nullable=True)
    op.alter_column('telegram', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment="User's last name",
               existing_nullable=True)
    op.alter_column('telegram', 'language_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment="User's language code",
               existing_nullable=True)
    op.alter_column('telegram', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='Status of Telegram integration: Disabled, Enabled, or Active',
               existing_comment='Status of Telegram connection: Disabled, Enabled, Active, or Inactive',
               existing_nullable=False,
               existing_server_default=sa.text("'Disabled'"))
    op.alter_column('telegram', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Soft delete timestamp',
               existing_nullable=True)
    op.drop_index('idx_telegram_channel', table_name='telegram')
    op.drop_index('idx_telegram_uid', table_name='telegram')
    op.drop_index('uq_telegram_user_chat', table_name='telegram')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_telegram_user_chat', 'telegram', ['user_id', 'channel_id'], unique=True)
    op.create_index('idx_telegram_uid', 'telegram', ['telegram_user_id'], unique=False)
    op.create_index('idx_telegram_channel', 'telegram', ['channel_id'], unique=False)
    op.alter_column('telegram', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('telegram', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='Status of Telegram connection: Disabled, Enabled, Active, or Inactive',
               existing_comment='Status of Telegram integration: Disabled, Enabled, or Active',
               existing_nullable=False,
               existing_server_default=sa.text("'Disabled'"))
    op.alter_column('telegram', 'language_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment=None,
               existing_comment="User's language code",
               existing_nullable=True)
    op.alter_column('telegram', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment="User's last name",
               existing_nullable=True)
    op.alter_column('telegram', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment="User's first name",
               existing_nullable=True)
    op.alter_column('telegram', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment="User's Telegram username",
               existing_nullable=True)
    op.alter_column('telegram', 'chat_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Chat title for groups/channels, NULL for DMs',
               existing_nullable=True)
    op.alter_column('telegram', 'chat_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='Type of chat: private, group, supergroup, or channel',
               existing_nullable=False,
               existing_server_default=sa.text("'private'"))
    op.alter_column('telegram', 'channel_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment="Chat ID: user's chat_id for DMs, group chat_id for groups",
               existing_nullable=False)
    op.alter_column('telegram', 'telegram_user_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='Telegram user ID who connected this chat',
               existing_nullable=True)
    op.create_index('uq_teams_user_tenant', 'teams', ['user_id', 'tenant_id', 'teams_user_id'], unique=True)
    op.create_index('idx_teams_user_id', 'teams', ['teams_user_id'], unique=False)
    op.create_index('idx_teams_tenant', 'teams', ['tenant_id'], unique=False)
    op.create_index('uq_slack_user_workspace_channel', 'slack', ['user_id', 'workspace_id', 'channel_id'], unique=True)
    op.create_index('idx_slack_workspace_id', 'slack', ['workspace_id'], unique=False)
    op.create_index('idx_slack_user_id', 'slack', ['user_id'], unique=False)
    op.alter_column('slack', 'channel_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Channel name for group channels, NULL for DMs',
               existing_nullable=True)
    op.alter_column('slack', 'channel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='DM channel ID (slack_user_id) or group channel ID',
               existing_nullable=False)
    op.drop_constraint('uq_user_guild_channel', 'discord', type_='unique')
    op.create_index('uq_discord_user_account', 'discord', ['user_id', 'discord_user_id'], unique=True)
    op.create_index('idx_discord_uid', 'discord', ['discord_user_id'], unique=False)
    op.create_index('idx_discord_guild', 'discord', ['guild_id'], unique=False)
    op.alter_column('discord', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('discord', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16),
               comment='Status of Discord connection: Disabled, Enabled, Active, or Inactive',
               existing_comment='Status of Discord integration: DISABLED, ENABLED, or ACTIVE',
               existing_nullable=False,
               existing_server_default=sa.text("'Disabled'"))
    op.alter_column('discord', 'global_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Discord display name',
               existing_nullable=True)
    op.alter_column('discord', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Discord username',
               existing_nullable=True)
    op.alter_column('discord', 'channel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='Discord channel ID - NULL for DMs',
               existing_nullable=True)
    op.alter_column('discord', 'guild_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='Discord server (guild) ID - NULL for DMs',
               existing_nullable=True)
    op.alter_column('discord', 'discord_user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='Discord user ID',
               existing_nullable=False)
    op.drop_column('discord', 'channel_name')
    op.drop_column('discord', 'guild_name')
    # Skip recreating idx_cases_links_case_id - already exists
    # op.create_index('idx_cases_links_case_id', 'cases_links', ['case_id'], unique=False)
    # ### end Alembic commands ###
