import {
  GlobeAltIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  TrashIcon,
  ChartBarIcon,
  BellIcon,
  EnvelopeIcon,
  BeakerIcon,
  LinkIcon,
  EyeIcon,
  PlusIcon,
  ClockIcon,
  ChatBubbleBottomCenterTextIcon,
  UserGroupIcon,
  SunIcon,
  MoonIcon,
  Bars3Icon,
  XMarkIcon,
  ShieldCheckIcon,
  ComputerDesktopIcon,
  RocketLaunchIcon,
  BuildingOfficeIcon,
  DocumentTextIcon,
  UserPlusIcon,
  ArrowPathIcon,
  WrenchScrewdriverIcon,
  BoltIcon,
  CalendarIcon,
  ClipboardDocumentListIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronUpDownIcon,
} from '@heroicons/react/24/outline';

import {
  GlobeAltIcon as GlobeAltIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  TrashIcon as TrashIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  BellIcon as BellIconSolid,
  EnvelopeIcon as EnvelopeIconSolid,
  BeakerIcon as BeakerIconSolid,
  LinkIcon as LinkIconSolid,
  EyeIcon as EyeIconSolid,
  PlusIcon as PlusIconSolid,
  ClockIcon as ClockIconSolid,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterTextIconSolid,
  UserGroupIcon as UserGroupIconSolid,
  SunIcon as SunIconSolid,
  MoonIcon as MoonIconSolid,
  Bars3Icon as Bars3IconSolid,
  XMarkIcon as XMarkIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  ComputerDesktopIcon as ComputerDesktopIconSolid,
  RocketLaunchIcon as RocketLaunchIconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  DocumentTextIcon as DocumentTextIconSolid,
  UserPlusIcon as UserPlusIconSolid,
  ArrowPathIcon as ArrowPathIconSolid,
  WrenchScrewdriverIcon as WrenchScrewdriverIconSolid,
  BoltIcon as BoltIconSolid,
  CalendarIcon as CalendarIconSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListIconSolid,
  ChevronUpIcon as ChevronUpIconSolid,
  ChevronDownIcon as ChevronDownIconSolid,
  ChevronUpDownIcon as ChevronUpDownIconSolid,
} from '@heroicons/react/24/solid';

export const icons = {
  outline: {
    globe: GlobeAltIcon,
    warning: ExclamationTriangleIcon,
    check: CheckCircleIcon,
    trash: TrashIcon,
    chart: ChartBarIcon,
    bell: BellIcon,
    envelope: EnvelopeIcon,
    test: BeakerIcon,
    link: LinkIcon,
    eye: EyeIcon,
    plus: PlusIcon,
    clock: ClockIcon,
    chat: ChatBubbleBottomCenterTextIcon,
    users: UserGroupIcon,
    sun: SunIcon,
    moon: MoonIcon,
    menu: Bars3Icon,
    close: XMarkIcon,
    shield: ShieldCheckIcon,
    desktop: ComputerDesktopIcon,
    rocket: RocketLaunchIcon,
    building: BuildingOfficeIcon,
    document: DocumentTextIcon,
    userPlus: UserPlusIcon,
    refresh: ArrowPathIcon,
    wrench: WrenchScrewdriverIcon,
    bolt: BoltIcon,
    calendar: CalendarIcon,
    clipboard: ClipboardDocumentListIcon,
    chevronUp: ChevronUpIcon,
    chevronDown: ChevronDownIcon,
    chevronUpDown: ChevronUpDownIcon,
  },
  solid: {
    globe: GlobeAltIconSolid,
    warning: ExclamationTriangleIconSolid,
    check: CheckCircleIconSolid,
    trash: TrashIconSolid,
    chart: ChartBarIconSolid,
    bell: BellIconSolid,
    envelope: EnvelopeIconSolid,
    test: BeakerIconSolid,
    link: LinkIconSolid,
    eye: EyeIconSolid,
    plus: PlusIconSolid,
    clock: ClockIconSolid,
    chat: ChatBubbleBottomCenterTextIconSolid,
    users: UserGroupIconSolid,
    sun: SunIconSolid,
    moon: MoonIconSolid,
    menu: Bars3IconSolid,
    close: XMarkIconSolid,
    shield: ShieldCheckIconSolid,
    desktop: ComputerDesktopIconSolid,
    rocket: RocketLaunchIconSolid,
    building: BuildingOfficeIconSolid,
    document: DocumentTextIconSolid,
    userPlus: UserPlusIconSolid,
    refresh: ArrowPathIconSolid,
    wrench: WrenchScrewdriverIconSolid,
    bolt: BoltIconSolid,
    calendar: CalendarIconSolid,
    clipboard: ClipboardDocumentListIconSolid,
    chevronUp: ChevronUpIconSolid,
    chevronDown: ChevronDownIconSolid,
    chevronUpDown: ChevronUpDownIconSolid,
  }
};

export function Icon({ name, variant = 'outline', className = '', size = 'md' }) {
  const sizeClasses = {
    xs: 'w-4 h-4',
    sm: 'w-5 h-5',
    md: 'w-6 h-6',
    lg: 'w-8 h-8',
    xl: 'w-10 h-10',
  };

  const IconComponent = icons[variant][name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" with variant "${variant}" not found`);
    return null;
  }

  return <IconComponent className={`${sizeClasses[size]} ${className}`} />;
}
